/**
 * placeProgression 스냅샷 재생성 스크립트.
 * 실행: npx tsx scripts/gen-progression-snapshot.ts
 *
 * 주의: 보정 로직을 의도적으로 바꿨을 때만 재생성하고,
 * 재생성 후 반드시 대표 키(C major A/B, C minor B)를 손검산으로 재확인할 것.
 * 앵커는 각 진행의 첫 코드(ii)의 canonical 배치다.
 */
import { writeFileSync } from 'node:fs';
import { placeProgression } from '../src/engine/progressions';
import type { Form, ProgressionType } from '../src/engine/types';

const out: Record<string, number[][]> = {};
for (const type of ['major', 'minor'] as ProgressionType[]) {
  for (const form of ['A', 'B'] as Form[]) {
    for (let keyPc = 0; keyPc < 12; keyPc++) {
      out[`${type}:${form}:${keyPc}`] = placeProgression(keyPc, type, form);
    }
  }
}

const lines = Object.entries(out)
  .map(([k, v]) => `  '${k}': ${JSON.stringify(v)},`)
  .join('\n');

writeFileSync(
  'src/engine/__tests__/progression.snapshot.ts',
  `// AUTO-GENERATED by scripts/gen-progression-snapshot.ts — 직접 수정하지 말 것.
// placeProgression의 동결 스냅샷: 12키 × {major,minor} × {A,B} = 48진행.
// 앵커는 첫 코드(ii)의 canonical 배치. 보정 로직 변경 시 재생성 + 손검산 필수.
export const PROGRESSION_SNAPSHOT: Record<string, number[][]> = {
${lines}
};
`,
);
console.log(`wrote ${Object.keys(out).length} progressions`);
